### ISSUE TITLE
Typo in monster schema

### ISSUE THREAD

**Issue by Tim-Willard** [jimbarnesrtp/pf2graphql#1]
https://github.com/jimbarnesrtp/pf2graphql/blob/3ae6c44f51ef3ae0e3c79f738dd0ddc37d86fe57/functions/src/schema.js#L131

One of the fields is listed as `famiyl` instead of `family`.

**Comment by jimbarnesrtp** [comment]
Thanks will fix and push in the morning!

**Comment by jimbarnesrtp** [comment]
resolved
